### ISSUE TITLE
Bug while NBU service returns duplicated rates

### ISSUE THREAD

**Issue by AndriiRuzhitskii** [AndriiRuzhitskii/rates#12]
java.lang.IllegalStateException: Failed to execute CommandLineRunner
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:801) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:782) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
    at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:769) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
    at com.example.DemoApplication.main(DemoApplication.java:25) [classes/:na]
Caused by: java.lang.IllegalStateException: Duplicate key Currency [id=0, r030=933, txt=Білоруський рубль, cc=BYN]
    at java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source) ~[na:1.8.0_91]
    at java.util.HashMap.merge(Unknown Source) ~[na:1.8.0_91]
    at java.util.stream.Collectors.lambda$toMap$58(Unknown Source) ~[na:1.8.0_91]
    at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[na:1.8.0_91]
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_91]
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_91]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_91]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:1.8.0_91]
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_91]
    at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:1.8.0_91]
    at com.example.converters.RateNbuConverter.convertList(RateNbuConverter.java:51) ~[classes/:na]
    at com.example.services.CurrencyServiceImpl.getAllCurrenciesOngoingDate(CurrencyServiceImpl.java:32) ~[classes/:na]
    at com.example.services.CurrencyServiceImpl.getCurrencies(CurrencyServiceImpl.java:44) ~[classes/:na]
    at com.example.DemoApplication.lambda$0(DemoApplication.java:31) [classes/:na]
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
    ... 6 common frames omitted

**Comment by AndriiRuzhitskii** [comment]
[{"r030":682,"txt":"Саудівський рiял","rate":6.954629,"cc":"SAR","exchangedate":"24.10.2016"},{"r030":702,"txt":"Сигапурський долар","rate":18.404721,"cc":"SGD","exchangedate":"24.10.2016"},{"r030":704,"txt":"Донг","rate":0.0011723,"cc":"VND","exchangedate":"24.10.2016"},{"r030":752,"txt":"Шведська крона","rate":2.88264,"cc":"SEK","exchangedate":"24.10.2016"},{"r030":756,"txt":"Швейцарський франк","rate":25.807415,"cc":"CHF","exchangedate":"24.10.2016"},{"r030":760,"txt":"Сирійський фунт","rate":0.121648,"cc":"SYP","exchangedate":"24.10.2016"},{"r030":949,"txt":"Турецька ліра","rate":8.332546,"cc":"TRY","exchangedate":"24.10.2016"},{"r030":934,"txt":"Туркменський новий манат","rate":7.332229,"cc":"TMT","exchangedate":"24.10.2016"},{"r030":818,"txt":"Єгипетський фунт","rate":2.937111,"cc":"EGP","exchangedate":"24.10.2016"},{"r030":826,"txt":"Фунт стерлінгів","rate":31.276899,"cc":"GBP","exchangedate":"24.10.2016"},{"r030":840,"txt":"Долар США","rate":25.662802,"cc":"USD","exchangedate":"24.10.2016"},{"r030":860,"txt":"Узбецький сум","rate":0.008372,"cc":"UZS","exchangedate":"24.10.2016"},{"r030":901,"txt":"Новий тайванський долар","rate":0.821664,"cc":"TWD","exchangedate":"24.10.2016"},{"r030":952,"txt":"Франк CFA-BCEAO","rate":0.0443129,"cc":"XOF","exchangedate":"24.10.2016"},{"r030":959,"txt":"Золото","rate":32436.499,"cc":"XAU","exchangedate":"24.10.2016"},{"r030":960,"txt":"СПЗ(спец.права запозичення)","rate":35.248681,"cc":"XDR","exchangedate":"24.10.2016"},{"r030":961,"txt":"Срiбло","rate":449.356,"cc":"XAG","exchangedate":"24.10.2016"},{"r030":962,"txt":"Платина","rate":23994.72,"cc":"XPT","exchangedate":"24.10.2016"},{"r030":964,"txt":"Паладiй","rate":16270.216,"cc":"XPD","exchangedate":"24.10.2016"},{"r030":978,"txt":"Євро","rate":27.936526,"cc":"EUR","exchangedate":"24.10.2016"},{"r030":980,"txt":"Гривня","rate":1.0,"cc":"UAH","exchangedate":"24.10.2016"},{"r030":985,"txt":"Злотий","rate":6.459163,"cc":"PLN","exchangedate":"24.10.2016"},{"r030":986,"txt":"Бразильський реал","rate":8.047285,"cc":"BRL","exchangedate":"24.10.2016"},{"r030":972,"txt":"Сомонi","rate":3.314472,"cc":"TJS","exchangedate":"24.10.2016"},{"r030":643,"txt":"Російський рубль","rate":0.41093,"cc":"RUB","exchangedate":"24.10.2016"},{"r030":933,"txt":"Білоруський рубль","rate":13.4727,"cc":"BYN","exchangedate":"24.10.2016"},{"r030":933,"txt":"Білоруський рубль","rate":13.4727,"cc":"BYN","exchangedate":"24.10.2016"},{"r030":944,"txt":"Азербайджанський манат","rate":15.948544,"cc":"AZN","exchangedate":"24.10.2016"},{"r030":36,"txt":"Австралійський долар","rate":19.579847,"cc":"AUD","exchangedate":"24.10.2016"},{"r030":51,"txt":"Вiрменський драм","rate":0.05493681,"cc":"AMD","exchangedate":"24.10.2016"},{"r030":975,"txt":"Болгарський лев","rate":14.844896,"cc":"BGN","exchangedate":"24.10.2016"},{"r030":124,"txt":"Канадський долар","rate":19.399018,"cc":"CAD","exchangedate":"24.10.2016"},{"r030":152,"txt":"Чилійське песо","rate":0.0386618,"cc":"CLP","exchangedate":"24.10.2016"},{"r030":156,"txt":"Юань Женьмiньбi","rate":3.794435,"cc":"CNY","exchangedate":"24.10.2016"},{"r030":191,"txt":"Куна","rate":3.882282,"cc":"HRK","exchangedate":"24.10.2016"},{"r030":203,"txt":"Чеська крона","rate":1.033882,"cc":"CZK","exchangedate":"24.10.2016"},{"r030":208,"txt":"Данська крона","rate":3.755768,"cc":"DKK","exchangedate":"24.10.2016"},{"r030":255,"txt":"Долар США по розр.з Iндiєю","rate":20.865,"cc":"   ","exchangedate":"24.10.2016"},{"r030":344,"txt":"Гонконгівський долар","rate":3.362049,"cc":"HKD","exchangedate":"24.10.2016"},{"r030":348,"txt":"Форинт","rate":0.0906147,"cc":"HUF","exchangedate":"24.10.2016"},{"r030":352,"txt":"Ісландська крона","rate":0.223699,"cc":"ISK","exchangedate":"24.10.2016"},{"r030":356,"txt":"Індійська рупія","rate":0.3884925,"cc":"INR","exchangedate":"24.10.2016"},{"r030":364,"txt":"Іранський ріал","rate":8.666E-4,"cc":"IRR","exchangedate":"24.10.2016"},{"r030":368,"txt":"Іракський динар","rate":0.02243,"cc":"IQD","exchangedate":"24.10.2016"},{"r030":376,"txt":"Новий ізраїльський шекель","rate":6.879781,"cc":"ILS","exchangedate":"24.10.2016"},{"r030":981,"txt":"Ларi","rate":11.309188,"cc":"GEL","exchangedate":"24.10.2016"},{"r030":392,"txt":"Єна","rate":0.2473134,"cc":"JPY","exchangedate":"24.10.2016"},{"r030":398,"txt":"Теньге","rate":0.077438,"cc":"KZT","exchangedate":"24.10.2016"},{"r030":410,"txt":"Вона","rate":0.0233453,"cc":"KRW","exchangedate":"24.10.2016"},{"r030":414,"txt":"Кувейтський динар","rate":86.559523,"cc":"KWD","exchangedate":"24.10.2016"},{"r030":417,"txt":"Сом","rate":0.378543,"cc":"KGS","exchangedate":"24.10.2016"},{"r030":422,"txt":"Ліванський фунт","rate":0.0173355,"cc":"LBP","exchangedate":"24.10.2016"},{"r030":434,"txt":"Лівійський динар","rate":18.915905,"cc":"LYD","exchangedate":"24.10.2016"},{"r030":484,"txt":"Мексіканське песо","rate":1.387707,"cc":"MXN","exchangedate":"24.10.2016"},{"r030":496,"txt":"Тугрик","rate":0.01170087,"cc":"MNT","exchangedate":"24.10.2016"},{"r030":498,"txt":"Молдовська лея","rate":1.283102,"cc":"MDL","exchangedate":"24.10.2016"},{"r030":554,"txt":"Новозеландський долар","rate":18.910732,"cc":"NZD","exchangedate":"24.10.2016"},{"r030":578,"txt":"Норвезька крона","rate":3.120075,"cc":"NOK","exchangedate":"24.10.2016"},{"r030":586,"txt":"Пакистанська рупія","rate":0.2492,"cc":"PKR","exchangedate":"24.10.2016"},{"r030":604,"txt":"Соль","rate":7.730985,"cc":"PEN","exchangedate":"24.10.2016"},{"r030":946,"txt":"Румунський лей","rate":6.513437,"cc":"RON","exchangedate":"24.10.2016"}]

**Comment by AndriiRuzhitskii** [comment]
Pull request #13 opened by AndriiRuzhitskii 
I1 Move all necessary to properties file; Bug while NBU service returns duplicated rates
